services:
  postgres:
    container_name:
      postgres
    image:
      postgres
    environment:
      POSTGRES_USER:
        jobapp
      POSTGRES_PASSWORD:
        jobapp
      PGDATA:
        /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped
  pgadmin:
    container_name:
      pgadmin
    image:
      dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL:
        ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD:
        ${PGADMIN_DEFAULT_PASSWORD:-jobapp}
      PGADMIN_CONFIG_SERVER_MODE:
        'False'
    volumes:
      - postgres:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - my-network
    restart: unless-stopped
  zipkin:
    image:
      openzipkin/zipkin
    container_name:
      zipkin
    ports:
      - 9411:9411
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  postgres:
  pgadmin: